apiVersion: v1
kind: Service
metadata:
    name: ikure-be-auth
spec:
    selector: 
      app: ikure
    ports:
      - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikure-be-auth
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels: 
        app: auth
    spec:
      containers:
        - name: ikure-be-auth
          image: registry.digitalocean.com/ikure-be-fe-1/ikure-be-auth 
      imagePullSecrets:
        - name: ikure-be-fe-1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec: 
  rules: 
    - host: dev.whimslive.com
      http: 
        paths: 
          - path: /auth
            backend: 
              serviceName: ikure-be-auth
              servicePort: 80
