kind: Service
apiVersion: v1
metadata:
  name: ikure-be-auth
  namespace: default
spec:
  ports:
    - name: tcp-80-5000
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    k8s-app: ikure-be-auth
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ikure-be-auth
# spec: 
#   replicas: 1
#   selector:
#     matchLabels:
#       app: auth
#   template:
#     metadata:
#       labels: 
#         app: auth
#     spec:
#       containers:
#         - name: ikure-be-auth
#           image: registry.digitalocean.com/ikure-be-fe-1/ikure-be-auth
#       imagePullSecrets:
#         - name: ikure-be-fe-1 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ikure-be-auth
  namespace: default
  labels:
    k8s-app: ikure-be-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ikure-be-auth
  template:
    metadata:
      name: ikure-be-auth
      labels:
        k8s-app: ikure-be-auth
    spec:
      containers:
        - name: ikure-be-auth
          image: 'registry.digitalocean.com/ikure-be-fe-1/ikure-be-auth'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec: 
  rules: 
    - host: dev.whimslive.com
      http: 
        paths: 
          - path: /auth
            backend: 
              serviceName: ikure-be-auth
              servicePort: 80
