apiVersion: v1
kind: Service
metadata:
    name: ikure-be-auth
spec:
    selector: 
      app: ikure
    ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikure-be-auth
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels: 
        app: auth
    spec:
      containers:
        - name: ikure-be-auth
          image: registry.digitalocean.com/ikure-be-fe-1/ikure-be-auth
          ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: ikure-be-fe-1 
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: auth-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec: 
#   rules: 
#     - host: dev.whimslive.com
#       http: 
#         paths: 
#           - path: /auth
#             backend: 
#               serviceName: ikure-be-auth
#               servicePort: 80
